### ISSUE TITLE
admin page access + logout button

### ISSUE THREAD

**Issue by TheSpartaPT** [ToxicRevolution/CSGORankMeWeb#11]
if you're not logged in you can still access the admin page and change every setting inside it, also there's no logout button whenever you're logged in + the login button stays there even if you're already logged in

**Comment by kennyLtv** [comment]
That you can whoops....

**Comment by APet74** [comment]
Not for long

**Comment by kennyLtv** [comment]
All should be fixed now, thank you for telling us

**Comment by TheSpartaPT** [comment]
still you can't logout when you're logged in and the login is still there when you're logged in, i'm the one that thanks you for replying and fixing bugs this fast

**Comment by kennyLtv** [comment]
you have all the current files?

**Comment by TheSpartaPT** [comment]
i'm going to download the new version with the admin.php fixed and check it out i think the lack of a logout button + still seeing the login button when already logged in is still there

**Comment by APet74** [comment]
will check 1 sec.

**Comment by TheSpartaPT** [comment]
if you don't have time i can fix it based on the fix you made for admin.php ...

**Comment by kennyLtv** [comment]
It all should all be fixed. We changed the nav to include a login/logout button based on if the user is authenticated or not. We also added a logout page to destroy and unset the user session, as well as not being able to view the admin page if you are not authenticated.

**Comment by TheSpartaPT** [comment]
testing still not working but for different reasons, now there is a logout button but if you click the it, it goes to the login page, but it doesn't log you out, because if you return to the main page you're still logged in

**Comment by kennyLtv** [comment]
I updated the logout.php can you try it with the new one?

**Comment by TheSpartaPT** [comment]
Right now i can't it is getting pretty late here, tomorow i will and report back the results

**Comment by APet74** [comment]
I also added some new files and functions to the admin menu.

**Comment by TheSpartaPT** [comment]
OK it now successfully logs you out haven't tried the new admin.php features because i'm not at home

**Comment by TheSpartaPT** [comment]
Aldo just got to my head,

here's a suggestion: add recaptcha to the login screen

**Comment by kennyLtv** [comment]
why add recaptcha?

**Comment by TheSpartaPT** [comment]
To stop bots from bruteforcing freely ...

**Comment by kennyLtv** [comment]
I need to talk with Andy about it some more but I think right this second its not something we want to implement. You can create another issue with it as a feature request. So that it is still here for us to see.
